version: '3.3'


services:
   db:
     image: mysql:5.7
     volumes:
       - /home/siddhanta.tripathi/Desktop/dockercompose-wordpress/mysql_dumb:/var/lib/mysql
     networks:
       - testing-network
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress 
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress


   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     networks:
       - testing-network

volumes:
    db_data:
networks:
    testing-network: